version: 2.1

workflows:
  main:
    jobs:
      - test-and-lint

jobs:
  test-and-lint:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run: make lint
      - run: make test-ci
